### ISSUE TITLE
Animation sheet support

### ISSUE THREAD

**Issue by tomrijnbeek** [amulware/awgraphics#1]
The library currently supports a quite extensive animation system, but another way of animation is the use of animation sheets, which is especially common in pixel-arty games. I am not sure if this fits within the theme of this library, or maybe it should be included in something like beardgame/utilities, or maybe should get its own library entirely.

I think it would be relatively simple to support quite a flexible set of tools. I think the main functionality should be to have the ability to cut an image in cells and define which of them form an animation. In the following image every row is a different animation for example.
![RPG Maker animation sheet](http://photos1.blogger.com/blogger/616/2952/1600/Character%20n%3F%3F8.1.png)

Maybe to support this, some general spritesheet functionality could be implemented as well. I am not sure if that is already an existing functionality in the library or that the animation system is used for that.

**Comment by amulware** [comment]
Can you specify what you mean by 'general spritesheet functionality'?

Otherwise, I agree that this would be a cool feature to add.
I was planning to add tools for packing multiple textures into a larger one, as well as other automatic ways of creating sprite sheets, so this may fit in well there.

I am not sure how exactly this could be combined with the existing animation system - or if it even should be, but that's definitely something to think about.

**Comment by amulware** [comment]
Bump for question @tomrijnbeek.

**Comment by tomrijnbeek** [comment]
With general spritesheet functionality I mean the functionality to load an image, divide it into tiles, and be able to draw those tiles easily. That is, without having to bother with setting the right quad(-size) and uv-coordinates yourself.

So... spritesheet would have a function with signatures similar to
```
void DrawTile(int i, int j, Rectangle targetRectangle);
void DrawTile(int i, int j, Vector3 position);
```

**Comment by amulware** [comment]
Understood. We may have to think about what makes the most sense.

I am not sure if there should be lots of different ways to address specific parts of textures. We already have the current sprite sheets, and fonts. This here would be a third that is somewhat in between.

Finding a combined solution (maybe a nice abstraction) would be great.

**Comment by amulware** [comment]
This doesn't exactly fit into the current library very well. We'd first have to implement much more of a content pipeline. A lot of that can be copied from TD I suspect, but I'll close this for now until it becomes more feasible or there is a stronger need.
