### ISSUE TITLE
Use factory methods instead of constructors

### ISSUE THREAD

**Issue by tomrijnbeek** [amulware/awgraphics#19]
Right now the library does a lot of work in the constructors. As in, actual work that involves calling to OpenGL. In the past we've had discussions about how doing work in constructors is bad. In general, I think it would be nice to move all the construction of objects that have their OpenGL equivalent created on construction done through public factory methods instead.

Factory methods also reveal intent a bit better in my opinion, since we can name them. For example, I think `new ShaderProgram(shaders)` looks less clear than `ShaderProgram.ForShaders(shaders)`.

It also allows us to move complex constructions to builders as well. For `ShaderProgram` we could go as far as making the construction pattern look something like:

```cs
var shaderProgram = ShaderProgram.NewBuilder()
    .SetVertexShader(vertexShader)
    .SetFragmentShader(fragmentShader)
    .SetPreLinkAction(() => Console.Log("pre-link!"))
    .Build();
```

**Comment by amulware** [comment]
I'm not sure I like the complexities of using builders for such simple things, not to mention there's a whole shader manager to make building shaders 'easier', but I can see the argument for factory methods. It's worth looking into.

**Comment by amulware** [comment]
Done in v2.
