### ISSUE TITLE
Split off animation

### ISSUE THREAD

**Issue by tomrijnbeek** [amulware/awgraphics#21]
Looking at the `Animation` part of this library, it feels somewhat strange that it is part of a graphics library that otherwise only focuses on rendering. I wonder if it would be better suited to have an `Animation` library that contains all this data, since it seems that it doesn't depend on the rest of the library, with the exception of the JSON serializers which could be moved to a common library, either a new one or an existing one such as `Bearded.Utilities`.

**Comment by amulware** [comment]
I can definitely see what you mean, especially since the animations have virtually no dependencies if I remember rightly.

**Comment by amulware** [comment]
Deprecated for now.
