### ISSUE TITLE
Clean up Program class

### ISSUE THREAD

**Issue by amulware** [amulware/awgraphics#5]
- [ ] remove unneeded and refactor used code
- [ ] rename to GameWindow
- [ ] check thread safety of multi threaded execution

**Comment by tomrijnbeek** [comment]
I would also recommend removing all references to obsolete OpenTK code.

**Comment by amulware** [comment]
That's a good point. We should in general consider updating OpenTK in beardgame/utilities as well.

**Comment by amulware** [comment]
Partially done, more will probably be handled in separate windowing package.
